### ISSUE TITLE
searching for questions/articles/recomendations

### ISSUE THREAD

**Issue by imanmahjoubi** [imanmahjoubi/ucla-project2#3]
## Category : Habit / Food
@knazim667  You will be searching good sources for the recommendation about food and habits

## Category : Activity/Sleep
@Elhanang2  you will be looking for articles and recommendations about sleeping and activities(workout, work, hobbies..)

**Comment by knazim667** [comment]
@imanmahjoubi there is problem with a localhost it cannot display the images ...
